// <auto-generated />
using System;
using CompanyAPI.contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyAPI.Migrations
{
    [DbContext(typeof(CorporationDbContext))]
    [Migration("20231220111653_ApiDb")]
    partial class ApiDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CompanyAPI.entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.ToTable("companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Company 1",
                            GroupId = 0L,
                            Image = "company1.jpg",
                            Name = "Company 1",
                            Sector = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Company 2",
                            GroupId = 0L,
                            Image = "company2.jpg",
                            Name = "Company 2",
                            Sector = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Company 3",
                            GroupId = 0L,
                            Image = "company3.jpg",
                            Name = "Company 3",
                            Sector = "Healthcare"
                        });
                });

            modelBuilder.Entity("CompanyAPI.entities.Corporation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("corporations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Corporation 1",
                            Image = "corporation1.jpg",
                            Name = "Corporation 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Corporation 2",
                            Image = "corporation2.jpg",
                            Name = "Corporation 2"
                        });
                });

            modelBuilder.Entity("CompanyAPI.entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Goal 1",
                            Image = "goal1.jpg",
                            Name = "Goal 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Goal 2",
                            Image = "goal2.jpg",
                            Name = "Goal 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Goal 3",
                            Image = "goal3.jpg",
                            Name = "Goal 3"
                        });
                });

            modelBuilder.Entity("CompanyAPI.entities.Company", b =>
                {
                    b.HasOne("CompanyAPI.entities.Corporation", null)
                        .WithMany("Companies")
                        .HasForeignKey("CorporationId");
                });

            modelBuilder.Entity("CompanyAPI.entities.Goal", b =>
                {
                    b.HasOne("CompanyAPI.entities.Company", null)
                        .WithMany("Goals")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("CompanyAPI.entities.Company", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("CompanyAPI.entities.Corporation", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
